# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'diplom' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for diplom
	
	#db
	pod 'RealmSwift'
	pod 'AppusViper', :git => 'git@gitlab.appus.software:ios/VIPER-template.git', :branch => 'develop'

end
